# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Publish DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build and publish
      run: |
          docker login --username ${{ vars.HUB_USERNAME }} --password ${{ secrets.HUB_PWD }}
          docker build . --tag ${{ vars.HUB_USERNAME }}/simple-rest-api:latest
          docker push ${{ vars.HUB_USERNAME }}/simple-rest-api:latest
